### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Jake Atakhanov",
    "company": "AJBuilding",
    "address": "2 Mindy dr Moorestown NJ 08057",
    "phone": "6142661131",
    "email": "J.atahanov@yahoo.com",
    "password": "secret1123"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "J.atahanov@yahoo.com",
    "password": "passwordTest"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkouYXRhaGFub3ZAeWFob28uY29tIiwiaWF0IjoxNjgyMzk2ODA3LCJleHAiOjE2ODIzOTc3MDd9.f-IfJMkqxOrE1V7KgvbPkWM-yPINVrMd97yTKyfWliI


### Get a refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkouYXRhaGFub3ZAeWFob28uY29tIiwiaWF0IjoxNjgxMTc0NzEyLCJleHAiOjE2ODM3NjY3MTJ9.ReKbw16jPnEw6vX8A99AR6yAffZBJ-P0u0xCuAYinrY
 

### Password reset request endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json 

{
    "email": "J.atahanov@yahoo.com"
}

### Update new password endpoints
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json 

{
    "email": "J.atahanov@yahoo.com",
    "pin": 759701,
    "newPassword": "passwordTest"
}

### User logout endpoint
DELETE  http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkouYXRhaGFub3ZAeWFob28uY29tIiwiaWF0IjoxNjgyNzM4NzEyLCJleHAiOjE2ODI3Mzk2MTJ9.Onycwgs__iwNDukbr1JYe9OyOoMr8URDlcHQvrfeGng